[package]
name = "leaflet"
version = "1.9.3"
edition = "2021"
publish = false
license = "MIT"

[dependencies]
wasm-bindgen = "0.2"
js-sys = "0.3"

[dependencies.web-sys]
version = "0.3"
features = ["Event", "HtmlElement", "MouseEvent"]

